# Generated by Django 5.2.5 on 2025-08-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoryName", models.CharField(max_length=100)),
                ("status", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productName", models.CharField(max_length=200)),
                ("image", models.JSONField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=100)),
                ("cover", models.CharField(blank=True, max_length=200)),
                ("price", models.BigIntegerField(default=0)),
                ("stock", models.BigIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("status", models.IntegerField(default=1)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="products", to="product.category"
                    ),
                ),
            ],
        ),
    ]
